### ISSUE TITLE
Code for Markov Random Fields?

### ISSUE THREAD

**Issue by MGarvinNYC** [tobybreckon/solomon-breckon-book#2]
One of the most interesting sections of your book deals with segmentation using MRFs (very well written).  Does code exist in Matlab or other  format?

**Comment by tobybreckon** [comment]
Sorry, there is no code examples for that particular sub-section.

**Comment by MGarvinNYC** [comment]
On Thu, Oct 11, 2018 at 11:04:05AM +0000, Toby Breckon wrote:
> Sorry, there is no code examples for that particular sub-section.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tobybreckon/solomon-breckon-book/issues/2#issuecomment-428913818

That would be valuable support for the book, to be sure.
Given that you don't have the code, can you provide any
leads to the code that was used to generate the segmented
underwater image?  Supposedly that functions in similar
fashion to the algorithms outlined in the chapter on
segmentation.

MGarvin
NYC
